/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VTokenRouteImport } from './routes/v.$token'
import { Route as AuthenticatedTrasladosRouteImport } from './routes/_authenticated/traslados'
import { Route as AuthenticatedSuperuserRouteImport } from './routes/_authenticated/superuser'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedPacientesIndexRouteImport } from './routes/_authenticated/pacientes.index'
import { Route as AuthenticatedSuperuserLinksRouteImport } from './routes/_authenticated/superuser.links'
import { Route as AuthenticatedSuperuserEstadoSistemaRouteImport } from './routes/_authenticated/superuser.estado-sistema'
import { Route as AuthenticatedSuperuserAuditRouteImport } from './routes/_authenticated/superuser.audit'
import { Route as AuthenticatedPacientesNuevoRouteImport } from './routes/_authenticated/pacientes.nuevo'
import { Route as AuthenticatedPacientesPatientIdRouteImport } from './routes/_authenticated/pacientes.$patientId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrasladosRoute = AuthenticatedTrasladosRouteImport.update({
  id: '/traslados',
  path: '/traslados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperuserRoute = AuthenticatedSuperuserRouteImport.update({
  id: '/superuser',
  path: '/superuser',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPacientesIndexRoute =
  AuthenticatedPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperuserLinksRoute =
  AuthenticatedSuperuserLinksRouteImport.update({
    id: '/links',
    path: '/links',
    getParentRoute: () => AuthenticatedSuperuserRoute,
  } as any)
const AuthenticatedSuperuserEstadoSistemaRoute =
  AuthenticatedSuperuserEstadoSistemaRouteImport.update({
    id: '/estado-sistema',
    path: '/estado-sistema',
    getParentRoute: () => AuthenticatedSuperuserRoute,
  } as any)
const AuthenticatedSuperuserAuditRoute =
  AuthenticatedSuperuserAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSuperuserRoute,
  } as any)
const AuthenticatedPacientesNuevoRoute =
  AuthenticatedPacientesNuevoRouteImport.update({
    id: '/pacientes/nuevo',
    path: '/pacientes/nuevo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacientesPatientIdRoute =
  AuthenticatedPacientesPatientIdRouteImport.update({
    id: '/pacientes/$patientId',
    path: '/pacientes/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/superuser': typeof AuthenticatedSuperuserRouteWithChildren
  '/traslados': typeof AuthenticatedTrasladosRoute
  '/v/$token': typeof VTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/pacientes/$patientId': typeof AuthenticatedPacientesPatientIdRoute
  '/pacientes/nuevo': typeof AuthenticatedPacientesNuevoRoute
  '/superuser/audit': typeof AuthenticatedSuperuserAuditRoute
  '/superuser/estado-sistema': typeof AuthenticatedSuperuserEstadoSistemaRoute
  '/superuser/links': typeof AuthenticatedSuperuserLinksRoute
  '/pacientes/': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/superuser': typeof AuthenticatedSuperuserRouteWithChildren
  '/traslados': typeof AuthenticatedTrasladosRoute
  '/v/$token': typeof VTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/pacientes/$patientId': typeof AuthenticatedPacientesPatientIdRoute
  '/pacientes/nuevo': typeof AuthenticatedPacientesNuevoRoute
  '/superuser/audit': typeof AuthenticatedSuperuserAuditRoute
  '/superuser/estado-sistema': typeof AuthenticatedSuperuserEstadoSistemaRoute
  '/superuser/links': typeof AuthenticatedSuperuserLinksRoute
  '/pacientes': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/superuser': typeof AuthenticatedSuperuserRouteWithChildren
  '/_authenticated/traslados': typeof AuthenticatedTrasladosRoute
  '/v/$token': typeof VTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/pacientes/$patientId': typeof AuthenticatedPacientesPatientIdRoute
  '/_authenticated/pacientes/nuevo': typeof AuthenticatedPacientesNuevoRoute
  '/_authenticated/superuser/audit': typeof AuthenticatedSuperuserAuditRoute
  '/_authenticated/superuser/estado-sistema': typeof AuthenticatedSuperuserEstadoSistemaRoute
  '/_authenticated/superuser/links': typeof AuthenticatedSuperuserLinksRoute
  '/_authenticated/pacientes/': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/chat'
    | '/superuser'
    | '/traslados'
    | '/v/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/pacientes/$patientId'
    | '/pacientes/nuevo'
    | '/superuser/audit'
    | '/superuser/estado-sistema'
    | '/superuser/links'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/chat'
    | '/superuser'
    | '/traslados'
    | '/v/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/pacientes/$patientId'
    | '/pacientes/nuevo'
    | '/superuser/audit'
    | '/superuser/estado-sistema'
    | '/superuser/links'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/superuser'
    | '/_authenticated/traslados'
    | '/v/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/pacientes/$patientId'
    | '/_authenticated/pacientes/nuevo'
    | '/_authenticated/superuser/audit'
    | '/_authenticated/superuser/estado-sistema'
    | '/_authenticated/superuser/links'
    | '/_authenticated/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SignupRoute: typeof SignupRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  VTokenRoute: typeof VTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/traslados': {
      id: '/_authenticated/traslados'
      path: '/traslados'
      fullPath: '/traslados'
      preLoaderRoute: typeof AuthenticatedTrasladosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/superuser': {
      id: '/_authenticated/superuser'
      path: '/superuser'
      fullPath: '/superuser'
      preLoaderRoute: typeof AuthenticatedSuperuserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pacientes/': {
      id: '/_authenticated/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AuthenticatedPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/superuser/links': {
      id: '/_authenticated/superuser/links'
      path: '/links'
      fullPath: '/superuser/links'
      preLoaderRoute: typeof AuthenticatedSuperuserLinksRouteImport
      parentRoute: typeof AuthenticatedSuperuserRoute
    }
    '/_authenticated/superuser/estado-sistema': {
      id: '/_authenticated/superuser/estado-sistema'
      path: '/estado-sistema'
      fullPath: '/superuser/estado-sistema'
      preLoaderRoute: typeof AuthenticatedSuperuserEstadoSistemaRouteImport
      parentRoute: typeof AuthenticatedSuperuserRoute
    }
    '/_authenticated/superuser/audit': {
      id: '/_authenticated/superuser/audit'
      path: '/audit'
      fullPath: '/superuser/audit'
      preLoaderRoute: typeof AuthenticatedSuperuserAuditRouteImport
      parentRoute: typeof AuthenticatedSuperuserRoute
    }
    '/_authenticated/pacientes/nuevo': {
      id: '/_authenticated/pacientes/nuevo'
      path: '/pacientes/nuevo'
      fullPath: '/pacientes/nuevo'
      preLoaderRoute: typeof AuthenticatedPacientesNuevoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacientes/$patientId': {
      id: '/_authenticated/pacientes/$patientId'
      path: '/pacientes/$patientId'
      fullPath: '/pacientes/$patientId'
      preLoaderRoute: typeof AuthenticatedPacientesPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSuperuserRouteChildren {
  AuthenticatedSuperuserAuditRoute: typeof AuthenticatedSuperuserAuditRoute
  AuthenticatedSuperuserEstadoSistemaRoute: typeof AuthenticatedSuperuserEstadoSistemaRoute
  AuthenticatedSuperuserLinksRoute: typeof AuthenticatedSuperuserLinksRoute
}

const AuthenticatedSuperuserRouteChildren: AuthenticatedSuperuserRouteChildren =
  {
    AuthenticatedSuperuserAuditRoute: AuthenticatedSuperuserAuditRoute,
    AuthenticatedSuperuserEstadoSistemaRoute:
      AuthenticatedSuperuserEstadoSistemaRoute,
    AuthenticatedSuperuserLinksRoute: AuthenticatedSuperuserLinksRoute,
  }

const AuthenticatedSuperuserRouteWithChildren =
  AuthenticatedSuperuserRoute._addFileChildren(
    AuthenticatedSuperuserRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedSuperuserRoute: typeof AuthenticatedSuperuserRouteWithChildren
  AuthenticatedTrasladosRoute: typeof AuthenticatedTrasladosRoute
  AuthenticatedPacientesPatientIdRoute: typeof AuthenticatedPacientesPatientIdRoute
  AuthenticatedPacientesNuevoRoute: typeof AuthenticatedPacientesNuevoRoute
  AuthenticatedPacientesIndexRoute: typeof AuthenticatedPacientesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedSuperuserRoute: AuthenticatedSuperuserRouteWithChildren,
  AuthenticatedTrasladosRoute: AuthenticatedTrasladosRoute,
  AuthenticatedPacientesPatientIdRoute: AuthenticatedPacientesPatientIdRoute,
  AuthenticatedPacientesNuevoRoute: AuthenticatedPacientesNuevoRoute,
  AuthenticatedPacientesIndexRoute: AuthenticatedPacientesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SignupRoute: SignupRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  VTokenRoute: VTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
